{
    'name': 'University Management',
    'author': 'Author Name',
    'category': '',
    'version': '17.0.0.1.0',
    'summary': 'Manage colleges, departments, programs and courses',
    'description': 'A module to manage university structure including colleges, departments, programs, courses and users.',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/default_data.xml',
        'views/base.xml',
        'views/college.xml',
        'views/department.xml',
        'views/program.xml',
        'views/course.xml',
        'views/student.xml',
        'views/doctor.xml',
        'views/admin.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
