from . import college
from . import department
from . import program
from . import course
from . import course_outcome
from . import student
from . import doctor
from . import university_admin
from . import evaluation